// @generated by hand until diesel print-schema is run in CI or during local setup.
diesel::table! {
    use diesel::sql_types::*;
    use diesel::sql_types::Timestamptz;

    api_call_logs (id) {
        id -> Uuid,
        api_name -> Text,
        http_method -> Text,
        path -> Text,
        request_params -> Jsonb,
        response_status -> Int4,
        response_body -> Text,
        success -> Bool,
        error_message -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::sql_types::Timestamptz;

    orders (id) {
        id -> Uuid,
        epay_trade_no -> Text,
        product_id -> Nullable<Uuid>,
        product_info_id -> Uuid,
        created_at -> Timestamptz,
        paid_at -> Nullable<Timestamptz>,
        status -> Text,
        contact -> Text,
        order_password_hash -> Text,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::sql_types::Timestamptz;

    product_info (id) {
        id -> Uuid,
        image_base64 -> Nullable<Text>,
        name -> Text,
        details -> Text,
        price_cents -> Int8,
        active -> Bool,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::sql_types::Timestamptz;

    products (id) {
        id -> Uuid,
        product_info_id -> Uuid,
        content -> Text,
        status -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::sql_types::Timestamptz;

    site_settings (id) {
        id -> Bool,
        order_allocation_mode -> Text,
        updated_at -> Timestamptz,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    api_call_logs,
    orders,
    product_info,
    products,
    site_settings,
);
